// Auto-generated by parse-words.ts. Do not edit manually.
export const e52ToXngloInglishMap: Record<string, string> = {
  "apple": "xxpxl"
};
export const xngloInglishToHindiMap: Record<string, string> = {
  "xxpxl": "सेब"
};
