import fs from 'fs';
import path from 'path';

export function compileWordsMap() {
  const csvPath = path.join(process.cwd(), 'dxta', 'wrds.csv');
  
  if (!fs.existsSync(csvPath)) {
    console.error(`❌ Error: Words dictionary file not found at: ${csvPath}`);
    return;
  }

  console.log(`Reading 5-column dictionary from: ${csvPath}...`);
  const fileContent = fs.readFileSync(csvPath, 'utf-8');
  
  const lines = fileContent
    .split(/\r?\n/)
    .map(line => line.split(','))
    .filter(row => row.length >= 5);

  const e52ToXngloInglish: Record<string, string> = {};
  const xngloInglishToHindi: Record<string, string> = {};

  lines.forEach((row) => {
    const cleanCell = (cell: string) => cell.trim().replace(/^["']|["']$/g, '');

    const e52 = cleanCell(row[0]).toLowerCase();          // Column 1: E52
    const xngloInglish = cleanCell(row[2]).toLowerCase();  // Column 3: xNgloiNgliS
    const vinqi = cleanCell(row[4]);                       // Column 5: vinqi

    if (e52 && e52 !== 'e52' && e52 !== 'english') {
      e52ToXngloInglish[e52] = cleanCell(row[2]); // Keep original casing style for vocabulary if needed
      xngloInglishToHindi[xngloInglish] = vinqi;
    }
  });

  const outputFolder = path.join(process.cwd(), 'lib');
  const outputPath = path.join(outputFolder, 'englishToHindiData.ts');

  const fileTemplate = `// Auto-generated by parse-words.ts. Do not edit manually.
export const e52ToXngloInglishMap: Record<string, string> = ${JSON.stringify(e52ToXngloInglish, null, 2)};
export const xngloInglishToHindiMap: Record<string, string> = ${JSON.stringify(xngloInglishToHindi, null, 2)};\n`;

  fs.writeFileSync(outputPath, fileTemplate, 'utf-8');
  
  console.log(`\n✅ Success! Dual dictionaries compiled at: ${outputPath}`);
}

compileWordsMap();
