import fs from 'fs';
import path from 'path';

export function compileHindiWordsMap() {
  const csvPath = path.join(process.cwd(), 'dxta', 'wrds.csv');
  
  if (!fs.existsSync(csvPath)) {
    console.error(`❌ Error: Words dictionary file not found at: ${csvPath}`);
    return;
  }

  console.log(`Reading Hindi-Vinqi pairs from: ${csvPath}...`);
  const fileContent = fs.readFileSync(csvPath, 'utf-8');
  
  const lines = fileContent
    .split(/\r?\n/)
    .map(line => line.split(','))
    .filter(row => row.length >= 5);

  const hindiCommonWords: Record<string, string> = {};

  lines.forEach((row) => {
    const cleanCell = (cell: string) => cell.trim().replace(/^["']|["']$/g, '');

    const hindi = cleanCell(row[0]).toLowerCase();          // Column 1: Hindi/E52
    const vinqi = cleanCell(row[4]);                         // Column 5: vinqi

    // Only add if both hindi and vinqi are non-empty
    if (hindi && vinqi && hindi !== 'e52' && hindi !== 'english' && hindi.length > 0) {
      hindiCommonWords[hindi] = vinqi;
    }
  });

  const outputFolder = path.join(process.cwd(), 'lib');
  const outputPath = path.join(outputFolder, 'hindiCommonWords.ts');

  const fileTemplate = `// Auto-generated by parse-hindi-words.ts. Do not edit manually.
export const hindiCommonWordsMap: Record<string, string> = ${JSON.stringify(hindiCommonWords, null, 2)};\n`;

  fs.writeFileSync(outputPath, fileTemplate, 'utf-8');
  
  console.log(`\n✅ Success! Hindi-Vinqi word map compiled at: ${outputPath}`);
  console.log(`Generated map contains ${Object.keys(hindiCommonWords).length} word pairs.`);
}

compileHindiWordsMap();
